config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"  }

  root 'welcome#show'

    get "/user/settings"    => 'user#show',      as: :user_settings
    patch "/user/settings"  => 'user#update',    as: :user_settings_update

    patch "/user/settings/slackchannel" =>
          'user#update_slack_channel_from_button',
          as: :user_settings_slack_channel

    post "/message" => "twilio#message"

end

app/models/slack_api_request.rb
SlackApiUrl = "https://slack.com/api/"

module SlackApiRequest
  def slack_api_test
    return HTTParty.get SlackApiUrl + "api.test", Authorization: current_user.slack_token
  end

  def slack_test_authentication
    return HTTParty.get SlackApiUrl + "auth.test", query: { "token": current_user.slack_token }
  end

  def slack_post_message(message, user, channel)
    return HTTParty.post \
                      SlackApiUrl + "chat.postMessage",
           query: {
             "token": user.slack_token,
                   "channel": channel,
                   "text": message,
                   "as_user": "true"
           }
  end

  def slack_get_channels(user)
    r = HTTParty.post SlackApiUrl + "channels.list", query: { "token": user.slack_token }
    r["channels"]
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  include UserHelpers
  include SlackApiRequest
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:slack]

  serialize :slack_data, JSON

  def self.from_omniauth(auth)
    where(slack_id: auth.uid).first_or_create do |user|
      user.email =                  auth.info.email
      user.password =               Devise.friendly_token[0,20]
      user.slack_data =             auth
      user.slack_default_channel =  "general"
      user.image =                  auth.info.image
    end
  end

  def self.new_with_session(params, session)
    binding.pry
    super.tap do |user|
      if data = session["devise.slack_data"] && session["devise.slack_data"]["extra"]["raw_info"]
        binding.pry
        user.email = data["email"] if user.email.blank?
        binding.pry
      end
    end
  end

  def slack_token
    slack_data["credentials"]["token"]
  end

  def encrypted_phone_number=(val)
    write_attribute(:encrypted_phone_number, hash_data(val))
  end

  def slack_team_name
    slack_data["info"]["team"]
  end

  def slack_channels
    channels = slack_get_channels(self)
    channels.map { |channel| channel["name"] }
  end

  def slack_user_name
    slack_data["info"]["user"]
  end

  def slack_nick_name
    slack_data["info"]["nickname"]
  end

end

app/models/user_helpers.rb
module UserHelpers
  def filter_phone_number phone_number
    phone_number.gsub(/\D/, "").reverse[0..9].reverse
  end

  def valid_phone_number? phone_number
    phone_number.gsub(/\D/,"").length == 10
  end

  def hash_data data
    Digest::SHA256.hexdigest(data)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception

  before_action :authenticate_user!, :except => :message
end

app/controllers/twilio_controller.rb
class TwilioController < ApplicationController
  protect_from_forgery except: :message

  include SlackApiRequest, UserHelpers
  def message
    @message = approved_params[:Body]
    @user = find_user_by_phone(phone_number_filter(approved_params[:From]))
    @channel = @user.slack_default_channel
    slack_post_message @message, @user, @channel
    head :ok
  end

  def approved_params
      params.permit(
      :Body,
      :From
    )
  end

  def find_user_by_phone phone_number
    User.all.find_by(encrypted_phone_number: hash_data(phone_number))
  end



  private

  def phone_number_filter number
    number[2..-1]
  end



end

app/controllers/user_controller.rb
class UserController < ApplicationController
  include UserHelpers, SlackApiRequest

  def show
    @user = current_user
    @channels = slack_get_channels(current_user)
  end

  def update_slack_channel_from_button
    current_user.slack_default_channel = params["slack_default_channel"]
    current_user.save
    redirect_to :back
  end

  def update
    pn = filter_phone_number(params["phone_number"])
    if valid_phone_number?(pn)
      current_user.encrypted_phone_number = pn
      current_user.slack_default_channel = params["user"]["slack_default_channel"]
      current_user.save
    else
      current_user.errors.add(:base, "The phone number you entered is invalid.")
    end
    if current_user.errors.any?
      redirect_to user_settings_path
      flash[:error] = current_user.errors.full_messages
    else
      flash[:notice] = "You have succesfully updated your settings."
      redirect_to root_path
    end
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  include SlackApiRequest
  def slack
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Slack") if is_navigational_format?
    else
        session["devise.slack_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end


    # user = User.where(slack_id: data.uid).first_or_create! do |u|
    #   u.email                   = data.info.email
    #   u.password                = SecureRandom.hex 64
    #   u.slack_data              = data.to_h
    #   u.slack_default_channel   = "general"
    # end

    # sign_in user
    # redirect_to user_settings_path, notice: "Signed in with Slack"
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def show
    @user = current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "SlackersSlack" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">SlackersSlack</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
           <li><%#= link_to "Link1", "/path1"  %></li>
            <li><%#= link_to "Link2", "/path2"  %></li>
            <li><%#= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>


    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/index.html.erb
<h1>Welcom</h1>

app/views/user/show.html.erb
<h1>Additional Account Information</h1>
<%=  bootstrap_form_for @user, url: user_settings_update_path do |f|  %>
<%= label_tag(:phone_number, "Phone Number") %>
<%= text_field_tag(:phone_number) %>
<%= f.select(:slack_default_channel, @channels.map { |channel| channel["name"] }) %>
<button class="btn btn-primary">Save</button>
<% end %>

app/views/welcome/after_callback.html.erb
<h1>Additional Account Information</h1>
<%=  bootstrap_form_for @user, url: after_callback_save_path do |f|  %>
<%= label_tag(:phone_number, "Phone Number") %>
<%= text_field_tag(:phone_number) %>
<%= f.select(:slack_default_channel, @channels.map { |channel| channel["name"] }) %>
<button class="btn btn-primary">Save</button>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome</h1>

app/views/welcome/show.html.erb
<div>
  <img src="<%= @user.image %>" alt="slack_profile_image" class="img-rounded">
</div>

<div class="btn-group-vertical" role="group" aria-label="...">

  <div class="btn-group" role="group">
    <button type="button" class="btn btn-default btn-lg dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <%= "@" + @user.slack_user_name %>
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete  %></li>
      <li><%= link_to "Settings", user_settings_path %></li>
    </ul>
  </div>

  <div class="btn-group" role="group">
    <button type="button" class="btn btn-default btn-lg dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <%= "#" + @user.slack_default_channel %>
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <% @user.slack_channels.each do |channel| %>
      <li><%= link_to channel, user_settings_slack_channel_path(:slack_default_channel => channel), method: :patch %></li>
      <% end %>
    </ul>
  </div>

  <a type="button" class="btn btn-default btn-lg btn-block">
    <%= @user.slack_team_name %>
  </a>
</div>